### ISSUE TITLE
Unable to prisma deploy

### ISSUE THREAD

**Issue by adetoola** [prisma/prisma-cloud-feedback#238]
I have `prisma` installed globally.
Running `prisma -v` returns `prisma/1.23.1 (windows-x64) node-v11.1.0`
This same issue has resurfaced in the latest version of prisma@1.23.1

However, I when I ran `prisma deploy` I get the following error:
```
 !    Your `cluster` property in the prisma.yml is missing the workspace slug.
 !    Make sure that your `cluster` property looks like this: <workspace>/<cluster-name>. You can also remove
 !    the cluster property from the prisma.yml
 !    and execute prisma deploy again, to get that value auto-filled.

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"
```

Finally, if I downgrage to one of the earliest version of `prisma` like `1.10.2`, I don't encounter any error.

This issue is related [Unable to prisma deploy or yarn dev (prisma/playground) after 1.7.1 upgrade. Running on Prisma Cloud](https://github.com/prisma/prisma-cloud-feedback/issues/137) which is marked closed.

**Comment by billfienberg** [comment]
I was able to fix this on my machine by adding my **slug** into my endpoint path between the top level domain and service.

## Format:
**Old format**: `https://${region}.prisma.sh/${service}/${stage}`
**Format**: `https://${region}.prisma.sh/${slug}/${service}/${stage}`

## For example:
**Before**: `https://us1.prisma.sh/comedian/dev`
**After**: `https://us1.prisma.sh/donald-glover/comedian/dev`

## Source:
**Docs**: https://www.prisma.io/docs/releases-and-maintenance/upgrade-prisma/upgrade-to-1.7-jgpt#example:-deploying-to-a-prisma-sandbox-in-the-cloud

**Comment by marylicious** [comment]
Thank you @billfienberg  i was having the same problem, i solved it by using your method but I couldn't see anything inside the Prisma console but a "Succesfully authenticathed" message. 
But the url was
`https://app.prisma.io/{MySlug}/services/onboarding/step-4`
so I just changed 
prisma endpoint like you said
`https://us1.prisma.sh/{MySlug}/blablabla/dev` 
and everything was solved.
Thank you for sharing your solution.

**Comment by adetoola** [comment]
This issue have been resolved in the latest version of prisma-cli

**Comment by DanS** [comment]
This issue still reproduces for me on prisma@1.29.1

**Comment by jeremyeaton89** [comment]
same issue with prisma@1.30.1

**Comment by shermix** [comment]
The same issue persists for me on Prisma CLI version: prisma/1.34.10 (linux-x64) node-v13.7.0
